server:
  port: 8090
  
#EUREKA CLIENT
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      defaultZone: http://localhost:8761/eureka
      #defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
      #defaultZone: http://eureka-server:8761/eureka

#RUTAS
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      
      - id: ms1-customer
        uri: lb://service-customer
        #uri: http://localhost:8080
        predicates:
        - Path=/api/ms1/**
        #localhost:8090/api/ms1/customer -> asi buscará el api en eureka y resolverá en el ms customer.
        filters:
        - RewritePath=/api/ms1/(?<x>.*), /$\{x}
        
      - id: ms2-profile
        uri: lb://service-profile
        #uri: http://localhost:8081
        predicates:
        - Path=/api/ms2/**
        #localhost:8090/api/ms2/typecustomer
        #localhost:8090/api/ms2/subtype
        filters:
        - RewritePath=/api/ms2/(?<x>.*), /$\{x}

      - id: ms3-creditcard
        uri: lb://service-creditcard
        predicates:
        - Path=/api/ms3/**
        filters:
        - RewritePath=/api/ms3/(?<x>.*), /$\{x}

      - id: ms4-savingaccount
        uri: lb://service-savingaccount
        predicates:
        - Path=/api/ms4/**
        filters:
        - RewritePath=/api/ms4/(?<x>.*), /$\{x}

      - id: ms5-currentaccount
        uri: lb://service-currentaccount
        predicates:
        - Path=/api/ms5/**
        filters:
        - RewritePath=/api/ms5/(?<x>.*), /$\{x}

      - id: ms6-fixedtermaccount
        uri: lb://service-fixedtermaccount
        predicates:
        - Path=/api/ms6/**
        filters:
        - RewritePath=/api/ms6/(?<x>.*), /$\{x}

      - id: ms7-creditcharge
        uri: lb://service-creditcharge
        predicates:
        - Path=/api/ms7/**
        filters:
        - RewritePath=/api/ms7/(?<x>.*), /$\{x}

      - id: ms8-transactioncurrent
        uri: lb://service-transactioncurrent
        predicates:
        - Path=/api/ms8/**
        filters:
        - RewritePath=/api/ms8/(?<x>.*), /$\{x}

      - id: ms9-transactionsaving
        uri: lb://service-transactionsaving
        predicates:
        - Path=/api/ms9/**
        filters:
        - RewritePath=/api/ms9/(?<x>.*), /$\{x}

      - id: ms10-transactionfixed
        uri: lb://service-transactionfixed
        predicates:
        - Path=/api/ms10/**
        filters:
        - RewritePath=/api/ms10/(?<x>.*), /$\{x}

      - id: ms11-transfer
        uri: lb://service-transfer
        predicates:
        - Path=/api/ms11/**
        filters:
        - RewritePath=/api/ms11/(?<x>.*), /$\{x}

      - id: ms12-reports
        uri: lb://service-reports
        predicates:
        - Path=/api/ms12/**
        filters:
        - RewritePath=/api/ms12/(?<x>.*), /$\{x}

      - id: ms13-creditpay
        uri: lb://service-creditpay
        predicates:
        - Path=/api/ms13/**
        filters:
        - RewritePath=/api/ms13/(?<x>.*), /$\{x}

      - id: ms14-yankiaccount
        uri: lb://service-yankiaccount
        predicates:
        - Path=/api/ms14/**
        filters:
        - RewritePath=/api/ms14/(?<x>.*), /$\{x}


