#EUREKA CLIENT
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      
#ROUTES
spring:
  cloud:
    gateway:
      routes:
      
      - id: service-customer
        uri: lb://service-customer
        predicates:
        - Path=/api/v1/customer/**
        filters: StripPrefix=2
      
      - id: service-profile
        uri: lb://service-profile
        predicates:
        - Path=/api/v1/profile/**
        filters: StripPrefix=2
