server:
  port: 8090
  
#EUREKA CLIENT
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      defaultZone: http://localhost:8761/eureka
      #defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
      #defaultZone: http://eureka-server:8761/eureka

#RUTAS
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      
      - id: ms1-customer
        uri: lb://service-customer
        #uri: http://localhost:8080
        predicates:
        - Path=/api/ms1/**
        #localhost:8090/api/ms1/customer -> asi buscará el api en eureka y resolverá en el ms customer.
        filters:
        - RewritePath=/api/ms1/(?<x>.*), /$\{x}
        
      - id: ms2-profile
        uri: lb://service-profile
        #uri: http://localhost:8081
        predicates:
        - Path=/api/ms2/**
        #localhost:8090/api/ms2/typecustomer
        #localhost:8090/api/ms2/subtype
        filters:
        - RewritePath=/api/ms2/(?<x>.*), /$\{x}

