#PORT
server:
  port: 8888
  
#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      #defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-server:8761/eureka #docker
    register-with-eureka: true
    fetch-registry: true
