server:
  port: 8081

#MONGO
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditcard
      
#EUREKA
eureka:
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
      #defaultZone: http://eureka-server:8761/eureka
      
