#MONGO
spring:
  data:
    mongodb:
      uri: mongo://localhost:27017/dbprofile
      
#EUREKA
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
