server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#MONGO
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbcustomerx2
      #host: mongodb
      #port: 27017
      #database: dbcustomer
      
#EUREKA
eureka:
  #instance:
    #prefer-ip-address: true
    #hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      #defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
