server:
  port: 8081

#MONGO
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbprofilex2
      
#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
