  
#MONGO
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbprofilex2
      #host: mongodb
      #port: 27017
      #database: dbcustomer
      
#EUREKA
eureka:
  instance:
    #prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
