server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#MONGO
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbprofilex2
      
#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
      
